### ISSUE TITLE
My Little Emotebox could not be verified for use in Firefox and has been disabled.

### ISSUE THREAD

**Issue by Light-Wave** [sebadorn/MLE#10]
In the latest version of Firefox, My Little Emotebox no longer works.

![Image](https://github.com/user-attachments/assets/c90d0bb1-6433-46c5-af2b-0a9d12b273e4)

The Learn more takes you here: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

Trying to download the addon for Firefox from sebadorn.de gives the following error

![Image](https://github.com/user-attachments/assets/71553b12-8ffa-455b-aa8d-4a24eeb165a4)

The remaining MLP roleplay community would greatly appreciate if you could take a look at this 😄

**Comment by sebadorn** [comment]
I didn't expect the extension to still be in use 😄 I will look into it. Seems there is a bit more wrong aside from the signing issue, the options page does not work anymore and I don't see the emote box.

The Chrome extension also has been unpublished from the Web Store by Google.

**Comment by Light-Wave** [comment]
Much appreciated!

**Comment by sebadorn** [comment]
Firefox version should be fixed now. I'm not sure if it auto-updates from the broken version, though.

Once it is through the review, it is available on addons.mozilla.org: https://addons.mozilla.org/firefox/addon/my-little-emotebox/

Or installing it manually should also work, by clicking this link to the [signed .xpi](https://sebadorn.de/mlp/mle/mle-webext.xpi). If that doesn't trigger the install dialog, maybe downloading it and dropping it into Firefox does.

**Comment by Light-Wave** [comment]
Thanks! Although clicking on one of the emotes in the emote box used to put the emote into the reply box. It doesn't seem to do that any more. Did that functionality perhaps break?

**Comment by Light-Wave** [comment]
Old Reddit on Firefox. Clicking the textarea first doesn't fix it. It seems to deselect the text area when an emote is clicked.
